[workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64","win-64"]

[dependencies]
requests = "*"
sqlalchemy = ">=2.0.15"
typer = "*"
types-requests = ">=2.32.4.20250913,<3"
packaging = ">=25.0,<26"

[pypi-dependencies]
simple_index_db = { path = ".", editable = true }

[tasks]
update-db = "simple-index-db update-db"
show-free-threaded = "simple-index-db show-free-threaded"
