[project]
authors = [{name = "Klaus Zimmermann", email = "klaus.zimmermann@quansight.com"}]
dependencies = [
    "sqlalchemy>=2.0.15",
]
name = "simple-index-db"
requires-python = ">= 3.11"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.dependencies]
msgspec = "*"
requests = "*"
sqlalchemy = "*"
typer = "*"
ipython = ">=9.6.0,<10"
pyqt = ">=5.15.11,<6"
matplotlib = ">=3.10.7,<4"

[tool.pixi.pypi-dependencies]
simple_index_db = { path = ".", editable = true }

[tool.pixi.tasks]
